server:
  port: 8218
spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        register: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    host: localhost
    port: 6379
    password: 123456     # 密码（默认为空）
    timeout: 5000        # 连接超时时间（毫秒）
    jedis:
      pool:
        max-active: 500 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: 100  # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 100   # 连接池中的最大空闲连接
        min-idle: 8   # 连接池中的最小空闲连接

logging:
 level:
  root: info